blank_issues_enabled: false
contact_links:
  - name: 📩 Get in touch!
    url: https://livewyer.io/contact
    about: If you have questions or would like to find out how LiveWyer engineering pods can add value, we'd be delighted to meet and discuss details.
